### ISSUE TITLE
GPX upload error

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#1143]
> J'ai essayer de rentrer une sortie et au moment de valider le tout : please consult the server logs : unexpected error
> 
> J'ai essayer de tout refaire et la fin est la même...

Currently 3 outing was created without issue.

**Comment by tsauerwein** [comment]
In the logs is this error: https://github.com/c2corg/v6_api/issues/580

Would you have more information about what data was provided to create the outing? Especially what was used as geometry?

**Comment by stef74** [comment]
> Entre 11h15 et 11h40 je dirai, j'ai fait plusieurs essais...
> 
> J'ai finalement réussi à remettre la sortie avec le minimum d'info pour voir ce qui bloque, et ça semble être la trace GPS... Pourtant il y a déjà une autre sortie avec trace GPS...
>

**Comment by stef74** [comment]
That confirm geometry is the issue ... ;-)

**Comment by tsauerwein** [comment]
Could we get this GPX file to test?

**Comment by stef74** [comment]
[2016-12-02 Pic Blanc du Galibier.zip](https://github.com/c2corg/v6_ui/files/639177/2016-12-02.Pic.Blanc.du.Galibier.zip)

**Comment by stef74** [comment]
I have tested to add a GPX fil on old outing ... nos issue with this one : 
[chavasse.zip](https://github.com/c2corg/v6_ui/files/639251/chavasse.zip)

**Comment by jpicheral** [comment]
When this file [CimeGollien.zip](https://github.com/c2corg/v6_ui/files/689575/CimeGollien.zip) is uploaded to this outing https://www.camptocamp.org/outings/829358/it/cime-de-gollien-spalla-ovest-per-il-col-gollien the track is displayed on map on the editing page, but it is not displayed on the map of the main outing page

**Comment by asaunier** [comment]
@jpicheral Thanks for the example GPX file!

I notice this file contains 2 waypoints (pretty far away by the way) in addition to the expected ``<trk>`` element:
```
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<gpx xmlns="http://www.topografix.com/GPX/1/1" creator="MapSource 6.15.11" version="1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">

  <metadata>
    <link href="http://www.garmin.com">
      <text>Garmin International</text>
    </link>
    <time>2016-12-09T16:20:04Z</time>
    <bounds maxlat="45.7484400" maxlon="7.2575060" minlat="45.5490810" minlon="7.1230890"/>
  </metadata>

  <wpt lat="45.7484400" lon="7.2189000">
    <ele>-0.1100000</ele>
    <time>2016-07-15T19:52:25Z</time>
    <name>BECCA FR</name>
    <sym>Waypoint</sym>
    <extensions>
      <gpxx:WaypointExtension xmlns:gpxx="http://www.garmin.com/xmlschemas/GpxExtensions/v3">
        <gpxx:DisplayMode>SymbolAndName</gpxx:DisplayMode>
      </gpxx:WaypointExtension>
    </extensions>
  </wpt>

  <wpt lat="45.7316210" lon="7.2575060">
    <ele>1209.4600000</ele>
    <time>2016-07-15T19:52:25Z</time>
    <name>START</name>
    <sym>Waypoint</sym>
    <extensions>
      <gpxx:WaypointExtension xmlns:gpxx="http://www.garmin.com/xmlschemas/GpxExtensions/v3">
        <gpxx:DisplayMode>SymbolAndName</gpxx:DisplayMode>
      </gpxx:WaypointExtension>
    </extensions>
  </wpt>

  <trk>
    <name>09-DIC-16 02: 09 DIC 2016 09:09</name>
    <extensions>
      <gpxx:TrackExtension xmlns:gpxx="http://www.garmin.com/xmlschemas/GpxExtensions/v3">
        <gpxx:DisplayColor>White</gpxx:DisplayColor>
      </gpxx:TrackExtension>
    </extensions>
    <trkseg>
      <trkpt lat="45.5788210" lon="7.1231530">
        <ele>1690.6200000</ele>
        <time>2016-12-09T08:09:39Z</time>
      </trkpt>
      <trkpt lat="45.5788000" lon="7.1230890">
        <ele>1691.5800000</ele>
        <time>2016-12-09T08:09:49Z</time>
      </trkpt>
...
```

The 2 waypoints and the track are indeed displayed in the editing form map. When saving the form, the API request only contains a point data instead of the line geometry (this is probably not the expected behaviour):
```
geometry: {
 geom:  "{"type":"Point","coordinates":[803604.2720875626,5740127.790046191]}"
}
```
This point geometry seems to be one of the 2 waypoints. I guess the edit form only takes into account the first geometry it finds (here a waypoint).

If I remove the 2 waypoints from the file, and keep only the track, the track is displayed as expected after uploading it.

**Comment by desnoes** [comment]
i have tested with the file provided by @jpicheral, the bug is fixed.

**Comment by asaunier** [comment]
There is still a problem with the track provided at https://github.com/c2corg/v6_ui/issues/1143#issuecomment-265714053

The file is actually loaded in the map of the outing editing/creating form and the UI send the following ``geometry`` object to the API:
```
geom: "{"type":"Point","coordinates":[714602.5181561863,5628074.236953052]}"
geom_detail: "{"type":"MultiLineString","coordinates":[[[714602.5181561863,5628074.236953052,1977.57,1480670251]],[[714602.4155196159,5628075.715928827,1978.53,1480670269],[714458.8441674637,5628131.045822671,1983.34,1480671093],[714226.7711929908,5628524.809089075,2014.1,1480671657],[714171.8787394485,5628770.612830997,2037.65,1480672119],[714274.9922137904,5628813.546292651,2051.11,1480672232],[714217.8230651541,5628834.491459539,2064.09,1480672313],[714266.3706528117,5628919.751728122,2084.76,1480672448],[714122.164812958,5629085.8636505315,2122.73,1480672731],[714044.0202670052,5629116.820128157,2137.15,1480672822],[714029.8562755592,5629184.174600205,2153.97,1480672926],[713803.3443998324,5629467.570798036,2193.87,1480673430],[713661.1073230968,5629502.068136115,2229.43,1480673637],[713442.1906315115,5629735.575810045,2291.92,1480674032],[713347.1482098703,5629778.817655401,2317.4,1480674411],[713342.8094325291,5629825.850337922,2326.53,1480674472],[713287.1145324373,5629842.360043255,2334.22,1480674555],[713218.9724880102,5629932.95262169,2368.35,1480674762],[713158.7148802895,5629911.410556169,2379.4,1480674841],[713136.4705187015,5629981.108783966,2396.22,1480674925],[713042.1185562019,5629980.554048783,2420.26,1480675084],[712833.5496012791,5630078.623814479,2460.63,1480675498],[712682.2337632845,5630222.091567003,2484.66,1480675675],[712497.1688279116,5630325.69831829,2513.98,1480675856],[712264.7786151539,5630402.413527001,2550.03,1480676108],[712021.611451173,5630622.260069531,2604.35,1480676458],[711934.5934171021,5630615.16688641,2621.65,1480677965],[711843.5445265333,5630694.248973422,2642.32,1480678107],[711761.3504558043,5630715.740070469,2652.9,1480678183],[711693.7962450802,5630795.932610811,2678.85,1480678340],[711579.084726951,5630829.985912544,2698.56,1480678474],[711510.8493745268,5630945.197490359,2712.5,1480678614],[711513.9191653327,5631080.039972562,2731.72,1480678749],[711403.9009771228,5631199.878154614,2747.1,1480678899],[711439.8334727294,5631268.886243393,2766.81,1480678987],[711408.9675501629,5631336.534212141,2772.58,1480679078],[711150.6286750458,5631566.998225857,2828.82,1480679477],[710880.5238084255,5631591.19952342,2876.4,1480679859],[710701.8970469347,5631485.8741149455,2910.53,1480680153],[710697.22236303,5631570.77636658,2934.08,1480680545],[710649.3185916473,5631625.493626927,2953.79,1480682412],[710664.2383756441,5631659.9992272835,2941.77,1480683089],[710960.385201489,5631631.504362304,2843.72,1480683446],[711043.2883996384,5631672.853007095,2814.4,1480683522],[711167.3399458717,5631840.600959372,2778.35,1480683548],[711300.0877039339,5631906.562243742,2735.57,1480683627],[711389.9049445246,5631896.297470959,2723.55,1480683644],[711581.9025906173,5631705.3772055665,2694.71,1480683761],[711695.0372347635,5631662.152528848,2677.89,1480683832],[711992.9475617178,5631805.7247742275,2572.63,1480683866],[712003.2952983803,5631761.918356048,2572.14,1480683913],[712141.5948154833,5631771.390346134,2552.92,1480683930],[712397.5636875095,5631848.26318087,2519.27,1480684028],[712510.819625373,5631972.035224243,2506.29,1480684150],[712725.4255364691,5631820.243291327,2581.28,1480685318],[712749.4800642969,5631793.795559993,2591.37,1480685402],[712713.3609526958,5631644.278825446,2607.23,1480686433],[712805.4455598069,5631465.821075995,2589.45,1480687150],[712999.1320561583,5631287.4461181965,2567.34,1480687267],[713105.2686784395,5631108.731240338,2537.06,1480687311],[713124.3312840778,5630994.495070502,2525.52,1480687365],[713678.294462482,5630595.313920589,2420.26,1480687606],[713837.6346880469,5630410.629271476,2394.78,1480687700],[713799.322871908,5630397.341428878,2389.01,1480687719],[713817.0325227191,5630319.041243811,2373.63,1480687730],[713943.9952517477,5630085.46563048,2349.12,1480687758],[714010.4764316361,5630021.287544753,2341.43,1480687769],[714116.4917490681,5630023.757454541,2327.49,1480687932],[714100.5642565129,5629821.359699143,2306.82,1480687982],[714219.8104965511,5629759.442009913,2294.8,1480688112],[714264.765770845,5629685.651156464,2288.08,1480688122],[714203.5657657111,5629567.536852163,2258.75,1480688239],[714291.0876540613,5629539.973095615,2245.78,1480688296],[714341.7906319635,5629483.2609944055,2240.49,1480688362],[714307.8642360325,5629378.448883191,2207.32,1480688401],[714349.2831795345,5629352.629050207,2200.11,1480688440],[714293.8122208624,5629295.337011196,2183.77,1480688497],[714373.123094516,5629272.660662873,2175.6,1480688522],[714354.4523891452,5629237.556697909,2165.99,1480688529],[714542.0832721766,5629057.548602837,2123.69,1480688680],[714562.116260948,5628916.30484722,2088.6,1480688718],[714525.530620493,5628888.901570166,2083.31,1480688723],[714541.8873276089,5628818.010022738,2072.74,1480688865],[714458.9934580328,5628829.4994792985,2063.61,1480688878],[714393.0627864223,5628795.202811441,2050.15,1480688889],[714247.3173757469,5628605.153805747,2016.02,1480689097],[714238.2572827663,5628512.818187383,2010.73,1480689120],[714457.360590346,5628146.007408894,1981.41,1480689298],[714600.2321436512,5628071.952455297,1972.28,1480689580]]]}"
```
but the API crashes because of 
```
sqlalchemy.exc.InternalError: (psycopg2.InternalError) LineString must have at least two points
CONTEXT:  SQL function "st_geomfromwkb" statement 1
```
See the related API issue at https://github.com/c2corg/v6_api/issues/580

**Comment by loicperrin** [comment]
I cannot upload a GPX file in my outing. When saving I get the error message "Failed saving the changes".
It is the first time I get error when uploading a GPX file. Here is the GPX file which causes pb.
[2017-01-21 0947__20170121_0947.zip](https://github.com/c2corg/v6_ui/files/721516/2017-01-21.0947__20170121_0947.zip)

**Comment by asaunier** [comment]
@loicperrin Have you tried saving your track on the demo?
I have just tried to create an outing with your track on the demo and had no error: http://www.demov6.camptocamp.org/outings/828375/fr/legette-du-mirantin-versant-e-ete

**Comment by loicperrin** [comment]
> Have you tried saving your track on the demo?

I have just tried and it works. Now it works also on Prod. Probably it was due to a temporary problem on Prod yesterday (a friend of mine had the same pb with his own track yesterday).

**Comment by desnoes** [comment]
I tested with the 3 tracks provided in this issue:
chavasse => OK
CimeGollien => OK
2016-12-02 Pic Blanc du Galibier => NOK. Message : 'Please consult the server logs : unexpected error'

**Comment by asaunier** [comment]
> 2016-12-02 Pic Blanc du Galibier => NOK. Message : 'Please consult the server logs : unexpected error'

I was a bit surprised because we pushed a fix that has been tested with this GPX file. See PR https://github.com/c2corg/v6_ui/pull/1390

But I have just realized this code is only used when clicking on the "Upload a GPS track" button ("Pic Blanc du Galibier" works as expected), not when dragging the GPX file to the map ("Pic Blanc du Galibier" causes an API error).

@desnoes Could you confirm you get the error when dragging the GPX file to the map, not when using the upload button?

**Comment by desnoes** [comment]
> @desnoes Could you confirm you get the error when dragging the GPX file to the map, not when using the upload button?

I confirm i used the dragg and drop option.

**Comment by desnoes** [comment]
I tested with the 3 tracks provided in this issue (FF) with dragg and drop option:
chavasse => OK
CimeGollien => OK
2016-12-02 Pic Blanc du Galibier => OK
