### ISSUE TITLE
Navigating in the guidebook

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#254]
I had several feedbacks saying that making the "guidebook" menu pointing to the routes list page and that having then to select an entry in the document types dropdown is not that intuitive.
In addition it makes an extra request to the API to show the list of routes even though the user is trying to reach the list of WP or outings.

We need to find a solution. At least 2 possibilities:
- replace the guidebook "home page" by a somehow static page asking "what are you looking for" and showing buttons towards the routes, WP, outings, images, books, ...
- making the later item directly available in the menu (but not as first level entries - even though having "outings" in the main menu would make sense since it's rather a "live conditions" section whereas the routes/WP/books are a kind of knowledge database). A bit like post.ch ?
- ???

The aim is to avoid having to open several pages to find what you want in the guidebook and to make the guidebook structure (WP, routes, outings, ...) more obvious.

**Comment by asaunier** [comment]
Related to https://github.com/c2corg/v6_ui/issues/244

**Comment by fjacon** [comment]
@ginold @asaunier where do we stand for this issue ?

**Comment by tsauerwein** [comment]
> replace the guidebook "home page" by a somehow static page asking "what are you looking for" and showing buttons towards the routes, WP, outings, images, books, ...

Yes, I agree that it would very useful to have a  "home page" for the guidebook. Maybe something similar to http://www.outdooractive.com/en/guide/ where you have a list of activities, areas/regions, waypoint types, ... which link to a search for routes, waypoints, ...

And a quick search "I'd like to go climbing/hiking/... in ..." like [here](http://www.outdooractive.com/en/) would also be nice.
![outdooractive-search](https://cloud.githubusercontent.com/assets/266474/14554750/21171808-02ef-11e6-8193-dfd0a3f7cef1.png)

**Comment by asaunier** [comment]
Some people at the association could not find the way to open the advanced search pages for WP or outings (default is routes) => the current dropdown to choose the document type seems not intuitive enough.

**Comment by ginold** [comment]
don't forget to have a look at #267

**Comment by fjacon** [comment]
To be discussed after alpha 3

**Comment by stef74** [comment]
@asaunier @fjacon can we close ?

**Comment by tsauerwein** [comment]
I am preparing a proposition on how this "homepage for the guidebook" could look like. I will share something in the next days.

**Comment by asaunier** [comment]
Anyway I think this issue is still relevant and should not be closed.

**Comment by tsauerwein** [comment]
Something like this:

![screencapture-localhost-6554-guidebook-1476818854618](https://cloud.githubusercontent.com/assets/266474/19493257/34002dba-957a-11e6-84db-62ec0bab60b3.png)

**Comment by stef74** [comment]
:+1:

**Comment by asaunier** [comment]
That's nice indeed.

About the header:
* would the activity icons be clickable? leading to what?
* how would the "region" input work?

**Comment by tsauerwein** [comment]
> would the activity icons be clickable? leading to what?

The idea is that you can select activities like with the advanced search filter. They probably should rather be gray than orange.

> how would the "region" input work?

Either we simply search for areas (like in the user filter preferences), or we do a real geo-coding (like with the search component in the map) and search in a bbox of ~20km around the position.

**Comment by asaunier** [comment]
> Either we simply search for areas

So that would open an area detail view page? Not sure that's really what people want.
Or maybe the advanced search page (of outings? routes? WP?) with the bbox of the selected area?

> search in a bbox of ~20km around the position.

You mean it would use the geonames service of the map search component? https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/map/search.js
That sounds interesting indeed. Then:
* it should rather be named "places" than "regions"
* the bbox (actually the zoom level of the map recentering) should be the same than when searching a place in the map component (actually same tool)
* then again: outings? routes? WP? I guess "routes" would be more consistent with the "Find a tour" title.

**Comment by stef74** [comment]
Open area page view is not probably and good idea.

By default we can open search on route (most use) on selected area or place (with geoname) ... use the simplest !

if you use geoname solution change the string by "near to" or something like that ...

**Comment by tsauerwein** [comment]
> So that would open an area detail view page? Not sure that's really what people want.
> Or maybe the advanced search page (of outings? routes? WP?) with the bbox of the selected area?

No, you select activities and an area, and then hit "Go". This will open the advanced search for routes with the made filters.

**Comment by asaunier** [comment]
A basic version here: https://github.com/c2corg/v6_ui/pull/857
I need help to go further. @ginold ?

**Comment by ginold** [comment]
@asaunier you want me to take your branch and finish it? to make it similar to the example of Tobias ?

**Comment by asaunier** [comment]
Use my branch, @tsauerwein 's or create a new one. Up to you :)

**Comment by ginold** [comment]
Do we have some images to use in cards for each doctype or should we rather use the default icons ? (like for example on the "not found" page).

**Comment by stef74** [comment]
To be quick use the same icon

**Comment by tsauerwein** [comment]
Images would probably be nicer.

**Comment by ginold** [comment]
@tsauerwein where did you get the photo you used for your mockup?

**Comment by tsauerwein** [comment]
I used photos from the "Concours Photo":
https://www.camptocamp.org/articles/809627/fr/concours-photo-sophie-2016
https://www.camptocamp.org/articles/673796/fr/concours-photo-sophie-2015

**Comment by desnoes** [comment]
The icon for the WP 'atterissage parapente' is not the correct one. Otherwise, it is ok.

**Comment by mgerbaux** [comment]
OK for me at this stage; nice work ! (we can discuss later what type of WP should be dispayed after some users' feedbacks)
A detail to improve later : words caesura is not correct in the circle when not enough place to display on one line
![capture du 2017-01-11 22-02-18](https://cloud.githubusercontent.com/assets/22116605/21866262/bb46d078-d849-11e6-89a6-fd5eb993b7d4.png)

**Take car that forum menu do not hit this page** (but probably it is due to the bug on this menu ?)

**Comment by celinestern** [comment]
@mgerbaux It's only with zoom 100%! Smaller or bigger zoom didn't make this thing!

**Comment by stef74** [comment]
@celinestern it's depend of your size of screen ... i have this rendering on my laptop not on my desktop

**Comment by desnoes** [comment]
Unconnected mode: when i click on the button 'topoguide' at the bottom of the page, it does not open the topoguide home page but the previous one.  The behavior should be the same wether you click on the topoguide in the left menu or on the button at the bottom.
![bug home topoguide non connecte](https://cloud.githubusercontent.com/assets/19892089/21883749/d4f32834-d8b0-11e6-9aee-c03bae3916bb.jpg)

**Comment by asaunier** [comment]
@desnoes Good catch!
Fixed by https://github.com/c2corg/v6_ui/pull/1352
I have also updated the link in the forum menu template (should be applied by hand in Discourse - except that this problem will probably prevent from doing it https://github.com/c2corg/v6_forum/issues/67)

**Comment by Kryst0f** [comment]
The top of the page is almost empty, with only seven activity icons.

**Comment by Kryst0f** [comment]
If we will add this guidebook static "home page" including outings, should we still have the outings link on the home page ? 

I don't like this static topo-guide home page because it's one more clic to get information from the home page (in comparison to the V5). Nevertheless, we should be logical. If we're implementing a topo-guide home page, we should remove the outings links from the home page.

**Comment by brunobesson** [comment]
@Kryst0f IMHO those comments should no happen on github, but at an earlier step (that doesn't mean it's too late to change anything, only it shouldn't be discussed here). The forums are more appropriate to discuss association-related issues. On github, we focus more on the technical and implementation part.

(and please try not to edit your comments as often)

**Comment by asaunier** [comment]
@stef74 What's remaining with this issue? Perhaps the styling changes done by @brunobesson ?
Since they all have been merged I think, perhaps we can tag this issue as "ready for demo"?

**Comment by stef74** [comment]
Yes some little improvement are needed in term of content font-size (not very homogeneous ... but not critical)

**Comment by stef74** [comment]
@asaunier just a little comments ... the police are too "bold"

**Comment by asaunier** [comment]
> just a little comments ... the police are too "bold"

I don't think the SA will make more styling changes. Up to the association to do them.

**Comment by desnoes** [comment]
The icon for the WP 'atterissage parapente' is still not the correct one.
The other bug (access in non-connected mode) is fixed.

**Comment by brunobesson** [comment]
@desnoes I think it's best to close this issue and open antoher one for the problem you're mentioning. Do you agree?

**Comment by desnoes** [comment]
@brunobesson: that's fine for me. I open a new issue

**Comment by brunobesson** [comment]
All the more because the problem exists for paragliding landing cards too.
