### ISSUE TITLE
Image uploader issues

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#383]
* [x] The "Add images" button should not appear all the time:
  * collaborative documents: only to authenticated users
  * personal documents (outings): only to associated users

**Comment by ginold** [comment]
private or collaborative is defined by `protected`?
protected : false == collaborative and private : true == private?

**Comment by asaunier** [comment]
Nope, ``protected`` just means the document cannot be edited (or only by the moderators). It used for documents subject to "editing wars" or for sensitive documents (for instance the status of the association: http://www.camptocamp.org/articles/108205/fr/camptocamp-association-statuts).

Both collaborative or personal documents may be protected, even though personal documents are only editable by associated users so it's not really useful to protect them.

**Comment by asaunier** [comment]
Collaborative documents: waypoints, routes, books
Personal documents: outings, user profiles

Some document types may be either collaborative or personal: images, articles. For those document types an attribute is used to figure out if it is collaborative or not.
For images see: https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/image.py#L33 and https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L585-L589

**Comment by ginold** [comment]
it is already fixed thanks to the `documentService.isCollaborative()`, isn't it?

**Comment by asaunier** [comment]
The "add images" button still appears for instance in the outing pages despite my user is not associated to the outings.

**Comment by asaunier** [comment]
My bad: I had not paid attention that my user had "moderator" rights.
With a standard user, it works as expected.
