### ISSUE TITLE
Translations missing in Transifex

### ISSUE THREAD

**Issue by shortoland** [c2corg/v6_ui#627]
The following strings are now translated in last french version, and also not present in Transifex:

- [x] After disconnecting, there is the following confirmation message: "You have been disconnected"

![image1](https://cloud.githubusercontent.com/assets/20488365/18607271/7f9fa748-7cc8-11e6-9d37-887d5aab6f82.png)

- [ ] maps: + and - icons, up-left corner: tooltips "zoom in" and "zoom out"

- [x] http://c2corgv6.demo-camptocamp.com/routes#bbox=-857237,3946514,1657236,7253485:

Choices for "Configuration" and "Qualité du document" are not translated:

![image2](https://cloud.githubusercontent.com/assets/20488365/18607292/3330ff6e-7cc9-11e6-9fa6-c1cd14b7cf57.png)

- [x] Routes search results (http://c2corgv6.demo-camptocamp.com/routes#bbox=-857237,3946514,1657236,7253485): tooltips rock-rating and labande-rating not translated:

![image3](https://cloud.githubusercontent.com/assets/20488365/18607313/e3b62c92-7cc9-11e6-8b83-2b63e545299a.png)

- [x] Route creation (http://c2corgv6.demo-camptocamp.com/routes/add)
Button "Upload a GPS track".

![image4](https://cloud.githubusercontent.com/assets/20488365/18607357/76700242-7cca-11e6-8c76-1c772b52e471.png)

- [ ] Possibles associations categories not translated:

![image5](https://cloud.githubusercontent.com/assets/20488365/18607366/aa081220-7cca-11e6-99d0-c409f6efafb2.png)

- [x] Summary (http://c2corgv6.demo-camptocamp.com/routes/add):
Qualities of document not translated:

![image6](https://cloud.githubusercontent.com/assets/20488365/18607415/f310c984-7ccb-11e6-99f4-b93656c8f71f.png)

- [x] WP creation, "Références cartographiques" help not translated:

![image7](https://cloud.githubusercontent.com/assets/20488365/18607442/0de81bda-7ccd-11e6-98c4-b2f293cb24b9.png)

- [x] Sorties search: Filters "Evaluation des conditions", "Quality" and  "Fréquentation" not translated:

![image8](https://cloud.githubusercontent.com/assets/20488365/18607486/1913d34a-7cce-11e6-8f5b-677788ad26cf.png)

- [x] "Sortie" viewing (http://c2corgv6.demo-camptocamp.com/outings/736831/fr/mont-blanc-de-cheilon-versant-w): Values for remontées mécaniques, refuge and glacier non translated:

![image9](https://cloud.githubusercontent.com/assets/20488365/18607506/7a078890-7cce-11e6-9284-88fbef606d23.png)

- [x] "Sortie" creation (http://c2corgv6.demo-camptocamp.com/outings/add):
Button "Several days" +help for itinéraire emprunté, durée, météo, conditions and commentaires personnels not translated:

![image10](https://cloud.githubusercontent.com/assets/20488365/18607516/aa86ae92-7cce-11e6-9be1-3ac0bd8053f6.png)

![image11](https://cloud.githubusercontent.com/assets/20488365/18607525/d6bb3fbe-7cce-11e6-8a35-dd3085da946c.png)

**Comment by asaunier** [comment]
OK, thanks for the report.

@fbunoz has already made a related report at https://github.com/c2corg/v6_ui/issues/602
I copy-paste here his example and close it as duplicate.

> Il manque toutes les options des champs :
- route_type
- route_configuration_type
- climbing_outdoor_type
- rock_type
- cotation globale alpi (et oui, en DE ce ne sont pas les même symboles)
- matériel de glacier
- déneigement
- type de transport en commun
- public_transportation_rating
- climbing_styles
- pluie
- adapté aux enfants

**Comment by asaunier** [comment]
@shortoland @fbunoz I have pushed changes that fix most of the missing translations I think. There are still some strings that are not translated yet (simple search and some map tools).
The new strings have been pushed to Transifex and are ready to be translated.

**Comment by asaunier** [comment]
Most of the reported problems should have been addressed by https://github.com/c2corg/v6_ui/pull/628 (may be tested on the demo)

Still remain:

> Possibles associations categories not translated

=> see https://github.com/c2corg/v6_ui/issues/629

> ￼ maps: + and - icons, up-left corner: tooltips "zoom in" and "zoom out"

A solution to translation those tooltips would be to change the map directive code to do something like:
```
new ol.control.Zoom({
  zoomInTipLabel: gettextCatalog.getString('Zoom In'),
  zoomOutTipLabel: gettextCatalog.getString('Zoom Out')
})
```
as in https://github.com/camptocamp/ngeo/blob/0b432ab0d8abeaa9a2f092419633a45d22078cb5/contribs/gmf/src/controllers/abstractmobile.js#L117-L130 or https://github.com/camptocamp/ngeo/blob/f4f745701bddfbac79dc16d39479f72d17c880a3/contribs/gmf/src/controllers/abstractdesktop.js#L91-L109
but that means explicitely redefining the map controls. Not sure it's worth making such changes for those 2 tooltips that are not very complicated to understand.
I would recommend to leave them untranslated.

**Comment by asaunier** [comment]
@shortoland could you test the demo and close the issue if it is fixed?

**Comment by shortoland** [comment]
@asaunier I agree concerning "zoom in" and "zoom out".

Still have some untranslated strings:

- [ ] Route creation (http://c2corgv6.demo-camptocamp.com/routes/add) Button "Upload a GPS track".

- [ ] Outings search: Filters "Evaluation des conditions" and "Fréquentation" not translated

- [ ] Outing viewing (http://c2corgv6.demo-camptocamp.com/outings/736831/fr/mont-blanc-de-cheilon-versant-w): Values for remontées mécaniques, refuge and glacier not translated

- [ ] Outing viewing (http://c2corgv6.demo-camptocamp.com/outings/736971/fr/aiguille-de-peclet-versant-w): values for "quantité de neige" and "qualité de la neige" not translated

**Comment by asaunier** [comment]
Thanks @shortoland I think those missing translations will be fixed by https://github.com/c2corg/v6_ui/pull/664 (not merged yet).

**Comment by asaunier** [comment]
@shortoland The demo has been updated.

**Comment by shortoland** [comment]
@asaunier OK, still one problem (Possibles associations categories not translated), but I think it now concerns another ticket, so I close this one.

**Comment by asaunier** [comment]
> OK, still one problem (Possibles associations categories not translated), but I think it now concerns another ticket, so I close this one.

Yes I think it's related to https://github.com/c2corg/v6_ui/issues/629
