### ISSUE TITLE
Incorrect behaviours of advanced search pages

### ISSUE THREAD

**Issue by shortoland** [c2corg/v6_ui#655]
- [ ] slider handles are not fully reset when clearing filters (see https://github.com/c2corg/v6_ui/pull/460#issuecomment-229400429)
- [x] Multi-select boxes sometimes become no longer updatable after interacting with some other filters (other multi-select boxes?). For instance:
  - Click on "Topoguide"
  - Select "escalade" activity
  - Click on "Tous les filtres" (please note that choices for "Quality du document" are not all clickable)
  - Click on "Voir les résultats"
  - Issue: it's impossible to modify "Activité"
- [x] Filtering any document (route, outing, WP) on quality returns wrong results

Alex said: 
- [ ] a problem with double-slider filters in the primary filters section:
  - move an handle of a slider to some position
  - scroll the list until the "sticky" buttons appear at the top of the list
  - click on "see all filters"
  - the slider filter that is then shown is not in the expected status (handle not at the right position)
  - if clicking on "view results", the original slider is shown in the expected status
  - no problem with other filter types (text input or checkbox panel)
  - no problem if clicking on "see all filters" when the primary section is shown
- [ ] sticky filter problem:
  ![screenshot from 2016-10-28 14-43-09](https://cloud.githubusercontent.com/assets/7814311/19806807/67999238-9d1d-11e6-8a81-b9c13c364a2a.png)

- [x] Route search (activity : Neige galce et mixte): the field associated to 'matériel glacier' are not dispalyed correctly (Chrome).
![bug matos glacier](https://cloud.githubusercontent.com/assets/19892089/21420302/3e277a74-c82d-11e6-8074-fe3ee7f96480.jpg)

#1252

**Comment by shortoland** [comment]
@asaunier No worries. I have had a new item on quality's filter.

**Comment by asaunier** [comment]
> Filtering any document (route, outing, WP) on quality returns wrong results

Seems related to the API or ElasticSearch (index problem?).

I think it once worked and that the ``qa`` parameter used to add a quality filter in the API request is correct: https://github.com/c2corg/v6_api/blob/master/c2corg_api/search/mapping.py#L54

I am currently rebuilding the ElasticSearch index in my own instance to see if the results are consistent with the quality filter.

**Comment by tsauerwein** [comment]
With https://github.com/c2corg/v6_api/pull/327 the quality field is an "enum range criteria", that is you can search for a range like `&qa=medium,excellent`. This will give you all the documents with a quality between medium and excellent. When searching for `&qa=medium` you will get documents with a quality greater-than-or-equal-to medium.

If this doesn't make sense, we can undo this change. So that  `&qa=medium` will only give you documents with a medium quality.

**Comment by asaunier** [comment]
Thanks for the explanation @tsauerwein 

The current filter (a list of checkboxes) is maybe not relevant: is it really useful to filter on several non-consecutive qualities (eg. "draft", "good", "excellent")?! It's probably more consistent to select a range of qualities: eg. from "average to excellent" or "good to excellent" or "excellent to excellent" (to get only the excellent docs.
I will change the filter to use a double-slider as for the ratings.

**Comment by loicperrin** [comment]
> Multi-select boxes sometimes become no longer updatable after interacting with some other filters (other multi-select boxes?).

I have also observed this kind of problem: in the list of activities I cannot select an activity (even when I use for the first time the advance search). This does not appear every time, but often.

**Comment by ginold** [comment]
In case anyone was wandering why activities cannot be selected anymore sometimes: I found the bug and i will try to fix it soon. Copying the DOM to the sticky-filters causes the problem.

**Comment by stef74** [comment]
@shortoland @loicperrin could you retest please

**Comment by asaunier** [comment]
I don't think http://www.demov6.camptocamp.org/ is up to date and takes the fix into account...

**Comment by asaunier** [comment]
@ginold could you have a look at the list in https://github.com/c2corg/v6_ui/issues/655#issue-179596500 and, if relevant, check items that have been fixed by your recent changes on the advanced search pages?

**Comment by ginold** [comment]
nothing new to check.

**Comment by stef74** [comment]
I don't understand what is the real status of this issue ...

**Comment by asaunier** [comment]
Have a look at the unchecked points of the initial comment.

**Comment by shortoland** [comment]
I think the following items are now solved: "Filtering any document (route, outing, WP) on quality returns wrong results", "sticky filter problem": I have checked the corresponding boxes

**Comment by ginold** [comment]
sticky filter problem is not solved : for example go on topoguide/waypoints and scroll down to the results and click all filters -> type and you will see that the types are displayed inside the box instead on it. It's ok if you are on the top of the list only.

**Comment by asaunier** [comment]
@desnoes Should we close this issue since you have opened dedicated issues for the remaining tasks?
