### ISSUE TITLE
I can edit an image that is not mine

### ISSUE THREAD

**Issue by dribagnac** [c2corg/v6_ui#972]
I can edit an image (ie informations of an image) that is not mine.

For example this image which belongs to another contributor
http://www.demov6.camptocamp.org/images/edit/821567/fr

   I can edit it, change some datas.
   When I press the save's button (the V), an error is displayed
Oops! Cette page n'existe pas ou est privée. (this page does not exist or is private)

   **But** datas are **saved** ! (ie reloading the page give to me the new datas)

   Furthemore, when the error's message is displayed, some part of the menu are shown (see screenshot).
![screenshot-www demov6 camptocamp org 2016-11-23 11-56-40](https://cloud.githubusercontent.com/assets/995825/20559277/ffbcabbc-b173-11e6-9aaa-fdf0940bcf06.png)

**Comment by stef74** [comment]
The menu is not the final version.

**Comment by tsauerwein** [comment]
Thanks for reporting! This should not be possible, because the image is not `collaborative` and you do not have moderator rights. I will investigate.

**Comment by tsauerwein** [comment]
The problem has been fixed in https://github.com/c2corg/v6_api/issues/527, but the demo has not yet been updated with the change.

**Comment by fjacon** [comment]
@tsauerwein problem fix but @arnaud-morvan we still have an error at bottom of the page.

see http://www.demov6.camptocamp.org/images/821567/fr/pointe-de-chalune

**Comment by tsauerwein** [comment]
This error message is related to the comments section, not really to the problem "I can edit an image that is not mine". You might want to open a separate issue.

**Comment by fbunoz** [comment]
> You might want to open a separate issue.

Done by arnaud : https://github.com/c2corg/v6_ui/issues/999

**Comment by stef74** [comment]
test ok
